"""
Tests for ResponseGenerator, Length Capping (Max 200 chars), and Error Handling.
"""

from unittest.mock import AsyncMock
import pytest
from app.services.cohost.models import (
    CoHostConfig,
    CoHostIntent,
    CoHostMessage,
    IntentType,
    ResponseStatus,
)
from app.services.cohost.response_generator import ResponseGenerator
from app.services.gemini.models import AIResponse, AIResponseStatus


@pytest.mark.asyncio
async def test_response_generator_success():
    """Verify clean response generation and normalization."""
    mock_ai = AsyncMock()
    mock_ai.request.return_value = AIResponse(
        request_id="req_1",
        stream_id="stream_1",
        status=AIResponseStatus.SUCCESS,
        text="Hey Alice! Glad to have you here in the stream today!",
        model="gemini-2.5-flash",
    )

    generator = ResponseGenerator(ai_manager=mock_ai)
    config = CoHostConfig()
    msg = CoHostMessage(
        stream_id="stream_1",
        message_id="m1",
        author_id="user_1",
        author_name="Alice",
        message_text="Hello Goddess!",
    )
    intent = CoHostIntent(intent_type=IntentType.GREETING, confidence=0.90)

    res = await generator.generate_response(msg, intent, config)

    assert res.status == ResponseStatus.APPROVED
    assert "Hey Alice!" in res.response_text
    assert len(res.response_text) <= 200


@pytest.mark.asyncio
async def test_response_generator_length_cap():
    """
    CRITICAL: Verify response longer than 200 characters is safely truncated to <= 200 chars.
    """
    mock_ai = AsyncMock()
    long_reply = (
        "This is an extraordinarily long response generated by Gemini that goes on and on "
        "discussing many different aspects of the live stream, strategies for winning the match, "
        "and telling everyone in the chat to subscribe right now!"
    ) * 3
    mock_ai.request.return_value = AIResponse(
        request_id="req_2",
        stream_id="stream_1",
        status=AIResponseStatus.SUCCESS,
        text=long_reply,
        model="gemini-2.5-flash",
    )

    generator = ResponseGenerator(ai_manager=mock_ai)
    config = CoHostConfig(max_response_length=200)
    msg = CoHostMessage(
        stream_id="stream_1",
        message_id="m2",
        author_id="user_2",
        author_name="Bob",
        message_text="Tell me a long story",
    )
    intent = CoHostIntent(intent_type=IntentType.CONVERSATION, confidence=0.80)

    res = await generator.generate_response(msg, intent, config)

    assert len(res.response_text) <= 200
    assert res.response_text.endswith("...")


@pytest.mark.asyncio
async def test_response_generator_ai_timeout_handling():
    """Verify Gemini timeout returns FAILED status without crashing."""
    mock_ai = AsyncMock()
    mock_ai.request.return_value = AIResponse(
        request_id="req_timeout",
        stream_id="stream_1",
        status=AIResponseStatus.TIMEOUT,
        text="",
        error_message="Request timed out after 8s",
    )

    generator = ResponseGenerator(ai_manager=mock_ai)
    config = CoHostConfig()
    msg = CoHostMessage(
        stream_id="stream_1",
        message_id="m3",
        author_id="user_3",
        author_name="Charlie",
        message_text="Hello",
    )
    intent = CoHostIntent(intent_type=IntentType.GREETING, confidence=0.85)

    res = await generator.generate_response(msg, intent, config)

    assert res.status == ResponseStatus.FAILED
    assert "timed out" in res.block_reason.lower()
